name: tafsir
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  data_connection_checker: ^0.3.4
  get: ^3.25.4
  google_fonts: ^1.1.2
  http: ^0.12.2
  # firebase_core: ^0.7.0
  # firebase_auth: ^0.20.1
  # cloud_firestore: ^0.16.0+1
  flutter_bloc: ^6.1.3
  freezed_annotation: 
  rxdart: ^0.25.0
  flutter_svg: ^0.19.0
  audioplayers: ^0.15.0
  flutter_zoom_drawer: ^1.0.5
  date_format: ^1.0.4
  location: ^3.0.1
  geolocator: ^5.1.3
  conditional_builder: ^1.0.2
  shared_preferences: ^0.4.0
  timer_builder: ^1.0.0

  # flutter_bloc: ^7.3.3
  # flutter_native_splash: ^1.3.1
  # flutter_secure_storage: ^4.2.1
  # flutter_svg: ^0.23.0+1
  # freezed: ^0.15.0+1
  # freezed_annotation: ^0.15.0
  # get_it:
  # hive: ^2.0.4
  # hive_flutter: ^1.1.0
  # image_picker: ^0.8.4+4
  # injectable: ^1.5.0
  # intl: ^0.17.0
  # page_transition: ^2.0.4
  # path_provider: ^2.0.6
  # simple_gesture_detector: ^0.2.0
  # slide_drawer: ^1.0.3
  # url_launcher: ^6.0.12
  flutter_overboard: ^1.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  # hive_generator: ^1.1.1
  injectable_generator: 
  freezed: ^0.12.2
  flutter_native_splash: ^0.3.2
  
 
  # lint: ^1.7.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # exampl
  assets:
    - assets/images/
    - assets/icons/
    - lib/core/zikr_json/


  fonts:
    - family: Sogeo
      fonts:
        - asset: assets/fonts/sui.ttf
    #     - asset: fonts/Raleway-Italic.ttf
    #       style: italic
    - family: ShareIcon
      fonts:
        - asset: assets/fonts/ShareIcon.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
